/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Stock, Etf, NewsAndReportsItem } from './types.ts';

export const TAIWAN_AI_STOCKS: Stock[] = [
  {
    id: "2330",
    name: "台積電",
    symbol: "2330.TW",
    sector: "晶圓代工與先進封裝 (CoWoS)",
    price: 2355.0,
    change: 60.0,
    changePercent: 2.61,
    volume: 89561.9, // 單位：張 (89561.9 * 1000 = 89,561,900 股 -> 8,956.19萬)
    avgVolume: 58157.08,
    volumeRatio: 1.54,
    revGrowthYoY: 38.5,
    revGrowthMoM: 5.2,
    maStrength: 3, // 3 > 2 > 1
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，多頭完美排列)",
    volumeUp: true,
    institutionalFlow: { foreign: 12450, investmentTrust: 1820, proprietary: 680 }
  },
  {
    id: "2317",
    name: "鴻海",
    symbol: "2317.TW",
    sector: "AI 伺服器整機組裝 (GB300/NVLink)",
    price: 385.0,
    change: 9.5,
    changePercent: 2.53,
    volume: 89500,
    avgVolume: 62000,
    volumeRatio: 1.44,
    revGrowthYoY: 28.3,
    revGrowthMoM: 4.1,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，高檔放量突破)",
    volumeUp: true,
    institutionalFlow: { foreign: 5120, investmentTrust: 950, proprietary: -320 }
  },
  {
    id: "2382",
    name: "廣達",
    symbol: "2382.TW",
    sector: "AI 伺服器整機與液冷機櫃組裝",
    price: 495.0,
    change: -5.0,
    changePercent: -1.00,
    volume: 18200,
    avgVolume: 15500,
    volumeRatio: 1.17,
    revGrowthYoY: 25.1,
    revGrowthMoM: -1.2,
    maStrength: 2,
    maDescription: "MA20 > MA60 > MA120 (中強多頭，短期 MA5 拉回守住月線)",
    volumeUp: false,
    institutionalFlow: { foreign: -850, investmentTrust: 1200, proprietary: 150 }
  },
  {
    id: "3017",
    name: "奇鋐",
    symbol: "3017.TW",
    sector: "AI 散熱模組 (3D VC / 液冷系統)",
    price: 855.0,
    change: 18.0,
    changePercent: 2.15,
    volume: 14500,
    avgVolume: 9200,
    volumeRatio: 1.57,
    revGrowthYoY: 42.1,
    revGrowthMoM: 8.4,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，液冷滲透率大增帶動)",
    volumeUp: true,
    institutionalFlow: { foreign: 3100, investmentTrust: 890, proprietary: 420 }
  },
  {
    id: "3324",
    name: "雙鴻",
    symbol: "3324.TW",
    sector: "AI 散熱模組 (水冷板 / 散熱主機)",
    price: 915.0,
    change: 22.0,
    changePercent: 2.46,
    volume: 8100,
    avgVolume: 5200,
    volumeRatio: 1.55,
    revGrowthYoY: 39.8,
    revGrowthMoM: 6.7,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，新機架拉貨潮起)",
    volumeUp: true,
    institutionalFlow: { foreign: 1850, investmentTrust: 640, proprietary: 110 }
  },
  {
    id: "6669",
    name: "緯穎",
    symbol: "6669.TW",
    sector: "AI 伺服器 (Hyperscale ODM)",
    price: 2450.0,
    change: -35.0,
    changePercent: -1.41,
    volume: 1150,
    avgVolume: 1600,
    volumeRatio: 0.72,
    revGrowthYoY: 31.2,
    revGrowthMoM: -2.3,
    maStrength: 2,
    maDescription: "MA20 > MA60 > MA120 (中強多頭，短線量縮整理中)",
    volumeUp: false,
    institutionalFlow: { foreign: -420, investmentTrust: 280, proprietary: -50 }
  },
  {
    id: "3037",
    name: "欣興",
    symbol: "3037.TW",
    sector: "ABF 載板 (高階 GPU 載板支援)",
    price: 222.0,
    change: 4.5,
    changePercent: 2.07,
    volume: 24500,
    avgVolume: 26000,
    volumeRatio: 0.94,
    revGrowthYoY: 15.4,
    revGrowthMoM: 3.8,
    maStrength: 1,
    maDescription: "MA60 > MA120 (初多頭，短期均線糾結，剛從底部翻揚)",
    volumeUp: false,
    institutionalFlow: { foreign: 980, investmentTrust: -150, proprietary: 80 }
  },
  {
    id: "3231",
    name: "緯創",
    symbol: "3231.TW",
    sector: "AI 伺服器 GPU 運算板與高速基板",
    price: 168.5,
    change: 3.5,
    changePercent: 2.12,
    volume: 54100,
    avgVolume: 35000,
    volumeRatio: 1.54,
    revGrowthYoY: 22.8,
    revGrowthMoM: 4.9,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，量價雙攻月線向上)",
    volumeUp: true,
    institutionalFlow: { foreign: 3450, investmentTrust: 1100, proprietary: 240 }
  },
  {
    id: "2308",
    name: "台達電",
    symbol: "2308.TW",
    sector: "AI 伺服器高效能電源供應器",
    price: 542.5,
    change: 8.5,
    changePercent: 1.59,
    volume: 12500,
    avgVolume: 10500,
    volumeRatio: 1.19,
    revGrowthYoY: 19.4,
    revGrowthMoM: 2.1,
    maStrength: 2,
    maDescription: "MA20 > MA60 > MA120 (中強多頭，高瓦數伺服器電源出貨強勁)",
    volumeUp: false,
    institutionalFlow: { foreign: 1520, investmentTrust: 340, proprietary: -90 }
  },
  {
    id: "2454",
    name: "聯發科",
    symbol: "2454.TW",
    sector: "手機與邊緣 AI 晶片 / 自研 ASIC 晶片",
    price: 1650.0,
    change: 45.0,
    changePercent: 2.80,
    volume: 9800,
    avgVolume: 6200,
    volumeRatio: 1.58,
    revGrowthYoY: 29.7,
    revGrowthMoM: 7.3,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，自研天璣AI晶片與ASIC動能增溫)",
    volumeUp: true,
    institutionalFlow: { foreign: 4210, investmentTrust: 750, proprietary: 310 }
  },
  {
    id: "3653",
    name: "健策",
    symbol: "3653.TW",
    sector: "均熱片 (ILS) / CPU 與 GPU 均熱結構件",
    price: 1780.0,
    change: 55.0,
    changePercent: 3.19,
    volume: 3200,
    avgVolume: 2100,
    volumeRatio: 1.52,
    revGrowthYoY: 34.6,
    revGrowthMoM: 5.8,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，超高溫散熱均熱片寡占)",
    volumeUp: true,
    institutionalFlow: { foreign: 1100, investmentTrust: 420, proprietary: 180 }
  },
  // 以下新增 9 檔台股個股，補足至 20 檔
  {
    id: "2301",
    name: "光寶科",
    symbol: "2301.TW",
    sector: "AI 高階電源供應與光電元件",
    price: 110.5,
    change: 1.5,
    changePercent: 1.38,
    volume: 15400,
    avgVolume: 12500,
    volumeRatio: 1.23,
    revGrowthYoY: 15.2,
    revGrowthMoM: 2.8,
    maStrength: 2,
    maDescription: "MA20 > MA60 (中多頭，高純度伺服器電源產品比重拉高)",
    volumeUp: false,
    institutionalFlow: { foreign: 850, investmentTrust: 310, proprietary: -120 }
  },
  {
    id: "2356",
    name: "英業達",
    symbol: "2356.TW",
    sector: "AI 伺服器主機板與整機組裝",
    price: 52.3,
    change: 1.2,
    changePercent: 2.35,
    volume: 42300,
    avgVolume: 31000,
    volumeRatio: 1.36,
    revGrowthYoY: 24.5,
    revGrowthMoM: 5.4,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，美系客戶訂單能見度佳)",
    volumeUp: true,
    institutionalFlow: { foreign: 1950, investmentTrust: 420, proprietary: 180 }
  },
  {
    id: "3443",
    name: "創意",
    symbol: "3443.TW",
    sector: "AI / HPC 客製化 ASIC 矽智財",
    price: 1250.0,
    change: -15.0,
    changePercent: -1.19,
    volume: 1650,
    avgVolume: 1800,
    volumeRatio: 0.92,
    revGrowthYoY: 18.4,
    revGrowthMoM: -1.5,
    maStrength: 2,
    maDescription: "MA20 > MA60 > MA120 (中強多頭，短線漲多高檔橫向整理)",
    volumeUp: false,
    institutionalFlow: { foreign: -180, investmentTrust: 240, proprietary: 40 }
  },
  {
    id: "3661",
    name: "世芯-KY",
    symbol: "3661.TW",
    sector: "高階 AI 客製化 ASIC 晶片設計",
    price: 2150.0,
    change: 45.0,
    changePercent: 2.14,
    volume: 2200,
    avgVolume: 1950,
    volumeRatio: 1.13,
    revGrowthYoY: 48.6,
    revGrowthMoM: 6.2,
    maStrength: 2,
    maDescription: "MA20 > MA60 > MA120 (中強多頭，北美超大型雲端客戶出貨擴大)",
    volumeUp: true,
    institutionalFlow: { foreign: 350, investmentTrust: 180, proprietary: -30 }
  },
  {
    id: "3035",
    name: "智原",
    symbol: "3035.TW",
    sector: "Edge AI / 客製化 ASIC 晶片量產",
    price: 312.0,
    change: 6.5,
    changePercent: 2.13,
    volume: 8900,
    avgVolume: 7100,
    volumeRatio: 1.25,
    revGrowthYoY: 22.4,
    revGrowthMoM: 4.8,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 (極強多頭，聯利及先進封裝量產效益顯著)",
    volumeUp: true,
    institutionalFlow: { foreign: 1120, investmentTrust: 280, proprietary: 110 }
  },
  {
    id: "2449",
    name: "京元電子",
    symbol: "2449.TW",
    sector: "NVIDIA H100 / Blackwell 晶片測試",
    price: 118.5,
    change: 3.5,
    changePercent: 3.04,
    volume: 18500,
    avgVolume: 14200,
    volumeRatio: 1.30,
    revGrowthYoY: 32.1,
    revGrowthMoM: 5.7,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，高階測試產能供不應求)",
    volumeUp: true,
    institutionalFlow: { foreign: 2840, investmentTrust: 860, proprietary: 320 }
  },
  {
    id: "2357",
    name: "華碩",
    symbol: "2357.TW",
    sector: "邊緣 AI PC 與企業級伺服器",
    price: 585.0,
    change: 12.0,
    changePercent: 2.09,
    volume: 5400,
    avgVolume: 4100,
    volumeRatio: 1.32,
    revGrowthYoY: 26.4,
    revGrowthMoM: 3.9,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，Copilot+ AI PC 爆發大受惠)",
    volumeUp: true,
    institutionalFlow: { foreign: 1420, investmentTrust: 380, proprietary: 210 }
  },
  {
    id: "2324",
    name: "仁寶",
    symbol: "2324.TW",
    sector: "AI 筆記型電腦與邊緣裝置代工",
    price: 35.8,
    change: -0.45,
    changePercent: -1.24,
    volume: 12500,
    avgVolume: 15100,
    volumeRatio: 0.83,
    revGrowthYoY: 10.4,
    revGrowthMoM: -1.2,
    maStrength: 2,
    maDescription: "MA20 > MA60 > MA120 (中強多頭，短期營收整理打底)",
    volumeUp: false,
    institutionalFlow: { foreign: -320, investmentTrust: 150, proprietary: -20 }
  },
  {
    id: "5269",
    name: "祥碩",
    symbol: "5269.TW",
    sector: "AI 高速傳輸 PCIe 介面晶片",
    price: 1680.0,
    change: 35.0,
    changePercent: 2.13,
    volume: 1100,
    avgVolume: 920,
    volumeRatio: 1.20,
    revGrowthYoY: 34.2,
    revGrowthMoM: 4.5,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，高頻寬通道升級大單進駐)",
    volumeUp: true,
    institutionalFlow: { foreign: 420, investmentTrust: 150, proprietary: 90 }
  }
];

export const US_AI_STOCKS: Stock[] = [
  {
    id: "NVDA",
    name: "NVIDIA",
    symbol: "NVDA",
    sector: "AI 晶片 / GPU / 全方位生態系",
    price: 132.50,
    change: 3.40,
    changePercent: 2.63,
    volume: 48900000,
    avgVolume: 32000000,
    volumeRatio: 1.53,
    revGrowthYoY: 112.4,
    revGrowthMoM: 12.1,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，Blackwell 晶片出貨超預期)",
    volumeUp: true,
    institutionalFlow: { netInstitutionalUSD: 4120 }
  },
  {
    id: "MSFT",
    name: "Microsoft",
    symbol: "MSFT",
    sector: "AI 軟體 / 雲端平台 (Azure AI)",
    price: 418.20,
    change: -1.50,
    changePercent: -0.36,
    volume: 18500000,
    avgVolume: 19000000,
    volumeRatio: 0.97,
    revGrowthYoY: 18.5,
    revGrowthMoM: 1.8,
    maStrength: 2,
    maDescription: "MA20 > MA60 > MA120 (中強多頭，短期高檔橫向震盪整理)",
    volumeUp: false,
    institutionalFlow: { netInstitutionalUSD: 850 }
  },
  {
    id: "AMD",
    name: "AMD",
    symbol: "AMD",
    sector: "AI 晶片 (MI325/MI350 伺服器晶片)",
    price: 145.60,
    change: 3.20,
    changePercent: 2.25,
    volume: 38900000,
    avgVolume: 24000000,
    volumeRatio: 1.62,
    revGrowthYoY: 38.0,
    revGrowthMoM: 9.2,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，第一季財報超預期帶動爆發)",
    volumeUp: true,
    institutionalFlow: { netInstitutionalUSD: 1980 }
  },
  {
    id: "AVGO",
    name: "Broadcom",
    symbol: "AVGO",
    sector: "AI 網通晶片 / 客製化 ASIC",
    price: 172.40,
    change: 2.80,
    changePercent: 1.65,
    volume: 3200000,
    avgVolume: 2200000,
    volumeRatio: 1.45,
    revGrowthYoY: 48.2,
    revGrowthMoM: 5.4,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，特用網絡交換器需求突進)",
    volumeUp: true,
    institutionalFlow: { netInstitutionalUSD: 1450 }
  },
  {
    id: "DELL",
    name: "Dell Technologies",
    symbol: "DELL",
    sector: "企業級 AI 伺服器與邊緣 AI",
    price: 122.50,
    change: -0.80,
    changePercent: -0.65,
    volume: 11000000,
    avgVolume: 13000000,
    volumeRatio: 0.85,
    revGrowthYoY: 21.6,
    revGrowthMoM: -0.8,
    maStrength: 2,
    maDescription: "MA20 > MA60 > MA120 (中強多頭，前波創高後拉回修正中)",
    volumeUp: false,
    institutionalFlow: { netInstitutionalUSD: -120 }
  },
  {
    id: "ANET",
    name: "Arista Networks",
    symbol: "ANET",
    sector: "AI 網路高速交換機 (800G/1.6T)",
    price: 385.40,
    change: 8.20,
    changePercent: 2.18,
    volume: 4100000,
    avgVolume: 2700000,
    volumeRatio: 1.51,
    revGrowthYoY: 34.5,
    revGrowthMoM: 7.2,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，乙太網路標準陣營擴張)",
    volumeUp: true,
    institutionalFlow: { netInstitutionalUSD: 890 }
  },
  {
    id: "SMCI",
    name: "Supermicro",
    symbol: "SMCI",
    sector: "液冷 AI 機架與伺服器組裝",
    price: 28.50,
    change: -0.90,
    changePercent: -3.06,
    volume: 18500000,
    avgVolume: 22000000,
    volumeRatio: 0.84,
    revGrowthYoY: 110.2,
    revGrowthMoM: -10.4,
    maStrength: 1,
    maDescription: "MA120 以上反壓重 (初多頭或打底整理，法規申報釐清進展中)",
    volumeUp: false,
    institutionalFlow: { netInstitutionalUSD: -890 }
  },
  {
    id: "TSM",
    name: "TSMC ADR",
    symbol: "TSM",
    sector: "高階晶圓代工 (ADR 折溢價指標)",
    price: 392.50,
    change: 10.00,
    changePercent: 2.61,
    volume: 16500000,
    avgVolume: 12000005,
    volumeRatio: 1.38,
    revGrowthYoY: 38.2,
    revGrowthMoM: 4.9,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，先進製程產能長期包檔)",
    volumeUp: true,
    institutionalFlow: { netInstitutionalUSD: 1680 }
  },
  {
    id: "QCOM",
    name: "Qualcomm",
    symbol: "QCOM",
    sector: "邊緣 AI 晶片 (手機 / NPU PC)",
    price: 168.20,
    change: 1.80,
    changePercent: 1.08,
    volume: 7800000,
    avgVolume: 8200000,
    volumeRatio: 0.95,
    revGrowthYoY: 16.8,
    revGrowthMoM: 2.3,
    maStrength: 2,
    maDescription: "MA20 > MA60 > MA120 (中強多頭，邊緣端 NPU 市佔穩步攀高)",
    volumeUp: false,
    institutionalFlow: { netInstitutionalUSD: 410 }
  },
  {
    id: "PLTR",
    name: "Palantir",
    symbol: "PLTR",
    sector: "AI 企業級決策軟體 (AIP 平台)",
    price: 58.40,
    change: 1.95,
    changePercent: 3.45,
    volume: 42000000,
    avgVolume: 28000000,
    volumeRatio: 1.50,
    revGrowthYoY: 45.3,
    revGrowthMoM: 8.9,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，商業客戶與主權AI合約爆发)",
    volumeUp: true,
    institutionalFlow: { netInstitutionalUSD: 1250 }
  },
  {
    id: "AMZN",
    name: "Amazon",
    symbol: "AMZN",
    sector: "AWS 雲端算力 / 自研 Trainium 晶片",
    price: 192.30,
    change: 1.50,
    changePercent: 0.79,
    volume: 24000000,
    avgVolume: 25000000,
    volumeRatio: 0.96,
    revGrowthYoY: 21.0,
    revGrowthMoM: 1.5,
    maStrength: 2,
    maDescription: "MA20 > MA60 > MA120 (心中強多頭，自研 AI ASIC 部署計畫推進)",
    volumeUp: false,
    institutionalFlow: { netInstitutionalUSD: 680 }
  },
  // 以下新增 9 檔美股個股，補足至 20 檔
  {
    id: "GOOGL",
    name: "Alphabet Class A",
    symbol: "GOOGL",
    sector: "AI 搜尋、大語言模型 Gemini 與 Cloud AI",
    price: 172.50,
    change: 1.80,
    changePercent: 1.05,
    volume: 25000000,
    avgVolume: 21000000,
    volumeRatio: 1.19,
    revGrowthYoY: 15.4,
    revGrowthMoM: 2.1,
    maStrength: 2,
    maDescription: "MA20 > MA60 > MA120 (中強多頭，Gemini 商業應用持續擴大)",
    volumeUp: false,
    institutionalFlow: { netInstitutionalUSD: 820 }
  },
  {
    id: "META",
    name: "Meta Platforms",
    symbol: "META",
    sector: "開源 Llama 大模型與 Meta AI 生態系",
    price: 485.60,
    change: 12.40,
    changePercent: 2.62,
    volume: 16500000,
    avgVolume: 12000000,
    volumeRatio: 1.38,
    revGrowthYoY: 21.8,
    revGrowthMoM: 3.2,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，廣告結合 AI 轉化率大幅拉高)",
    volumeUp: true,
    institutionalFlow: { netInstitutionalUSD: 1420 }
  },
  {
    id: "AAPL",
    name: "Apple Inc.",
    symbol: "AAPL",
    sector: "Apple Intelligence 終端 AI 生態系",
    price: 224.80,
    change: 3.20,
    changePercent: 1.44,
    volume: 48000000,
    avgVolume: 42000000,
    volumeRatio: 1.14,
    revGrowthYoY: 10.2,
    revGrowthMoM: 1.5,
    maStrength: 2,
    maDescription: "MA20 > MA60 > MA120 (中強多頭，硬體內建 AI 推升換機潮預期)",
    volumeUp: false,
    institutionalFlow: { netInstitutionalUSD: 640 }
  },
  {
    id: "INTC",
    name: "Intel Corporation",
    symbol: "INTC",
    sector: "x86 AI 處理器及 AI Foundry 晶圓代工",
    price: 25.40,
    change: -0.32,
    changePercent: -1.24,
    volume: 38040000,
    avgVolume: 42000000,
    volumeRatio: 0.91,
    revGrowthYoY: 4.8,
    revGrowthMoM: -2.3,
    maStrength: 1,
    maDescription: "均線仍在低檔糾結 (築底整理，AI PC 處理器出貨緩慢成長)",
    volumeUp: false,
    institutionalFlow: { netInstitutionalUSD: -180 }
  },
  {
    id: "MU",
    name: "Micron Technology",
    symbol: "MU",
    sector: "HBM3e 高頻寬記憶體與 AI 記憶體",
    price: 112.50,
    change: 4.80,
    changePercent: 4.46,
    volume: 24500000,
    avgVolume: 18000000,
    volumeRatio: 1.36,
    revGrowthYoY: 55.4,
    revGrowthMoM: 8.5,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，HBM 快遞缺貨溢價高漲)",
    volumeUp: true,
    institutionalFlow: { netInstitutionalUSD: 2150 }
  },
  {
    id: "ORCL",
    name: "Oracle Corp.",
    symbol: "ORCL",
    sector: "OCI 專屬 AI 雲端基礎架構與資料庫",
    price: 168.20,
    change: 3.50,
    changePercent: 2.13,
    volume: 8500000,
    avgVolume: 6100000,
    volumeRatio: 1.39,
    revGrowthYoY: 20.4,
    revGrowthMoM: 3.1,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，雲端巨頭排隊簽約算力租賃)",
    volumeUp: true,
    institutionalFlow: { netInstitutionalUSD: 980 }
  },
  {
    id: "CRM",
    name: "Salesforce Inc.",
    symbol: "CRM",
    sector: "Agentforce 企業級 AI 代理平台與 CRM AI",
    price: 285.40,
    change: 5.60,
    changePercent: 2.00,
    volume: 5200000,
    avgVolume: 4100000,
    volumeRatio: 1.27,
    revGrowthYoY: 14.5,
    revGrowthMoM: 1.8,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 (極強多頭，AI Agentforce 引發各大企業搶先試用)",
    volumeUp: true,
    institutionalFlow: { netInstitutionalUSD: 820 }
  },
  {
    id: "MRVL",
    name: "Marvell Technology",
    symbol: "MRVL",
    sector: "自研 ASIC 晶片及高速光纖通信組件",
    price: 72.50,
    change: 1.85,
    changePercent: 2.62,
    volume: 9800000,
    avgVolume: 7200000,
    volumeRatio: 1.36,
    revGrowthYoY: 28.5,
    revGrowthMoM: 4.8,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，AI 光通訊組件火爆成長)",
    volumeUp: true,
    institutionalFlow: { netInstitutionalUSD: 1100 }
  },
  {
    id: "ARM",
    name: "Arm Holdings",
    symbol: "ARM",
    sector: "節能 AI 處理器架構與邊緣計算授權",
    price: 138.40,
    change: 4.20,
    changePercent: 3.13,
    volume: 12500000,
    avgVolume: 8500000,
    volumeRatio: 1.47,
    revGrowthYoY: 42.1,
    revGrowthMoM: 7.2,
    maStrength: 3,
    maDescription: "MA5 > MA20 > MA60 > MA120 (極強多頭，v9 架構權利金比重持續攀高)",
    volumeUp: true,
    institutionalFlow: { netInstitutionalUSD: 1450 }
  }
];

export const TAIWAN_ONLY_ETFS: Etf[] = [
  {
    id: "0050",
    name: "元大台灣50",
    symbol: "0050.TW",
    price: 192.50,
    change: 2.80,
    changePercent: 1.48,
    volume: 15400,
    aiPurity: "高 (約 65% 權重為 AI 供應鏈龍頭)",
    topHoldings: [
      { name: "台積電", weight: 52.8 },
      { name: "鴻海", weight: 8.5 },
      { name: "聯發科", weight: 4.8 },
      { name: "廣達", weight: 2.2 }
    ],
    maStrength: 3,
    description: "台股最具代表性權值指標。台積電與鴻海佔據主要權重，是防守與成長兼備的大資金基石首選。"
  },
  {
    id: "00935",
    name: "野村臺灣創新科技",
    symbol: "00935.TW",
    price: 21.50,
    change: 0.35,
    changePercent: 1.65,
    volume: 28900,
    aiPurity: "極高 (約 80% 高純度 AI 供應鏈)",
    topHoldings: [
      { name: "台積電", weight: 32.1 },
      { name: "聯發科", weight: 11.2 },
      { name: "台達電", weight: 5.5 },
      { name: "奇鋐", weight: 4.8 }
    ],
    maStrength: 3,
    description: "專為創新科技設計，完整捕捉台灣液冷散熱、高速傳輸、IC設計等具備關鍵技術之隱形冠軍。"
  },
  {
    id: "0052",
    name: "富邦科技",
    symbol: "0052.TW",
    price: 168.40,
    change: 2.80,
    changePercent: 1.69,
    volume: 4500,
    aiPurity: "極高 (近 75% 為晶圓代工與零組件)",
    topHoldings: [
      { name: "台積電", weight: 61.2 },
      { name: "聯發科", weight: 5.2 },
      { name: "鴻海", weight: 4.8 },
      { name: "台達電", weight: 2.8 }
    ],
    maStrength: 3,
    description: "台積電權重極高，被譽為「小台積電」ETF。在先進製程爆發期，淨值隨台積電噴出具備強烈動能。"
  },
  {
    id: "00891",
    name: "中信關鍵半導體",
    symbol: "00891.TW",
    price: 17.20,
    change: 0.28,
    changePercent: 1.65,
    volume: 31200,
    aiPurity: "極高 (約 80% 半導體上下游龍頭)",
    topHoldings: [
      { name: "台積電", weight: 21.5 },
      { name: "聯發科", weight: 19.8 },
      { name: "日月光投控", weight: 8.5 },
      { name: "聯詠", weight: 4.2 }
    ],
    maStrength: 3,
    description: "聚焦台灣半導體領頭羊。除晶圓代工外，加碼 IC 設計與先進封裝比例，與 AI 晶片高成長契合。"
  },
  {
    id: "00929",
    name: "復華台灣科技優息",
    symbol: "00929.TW",
    price: 19.10,
    change: 0.12,
    changePercent: 0.63,
    volume: 98000,
    aiPurity: "高 (100% 聚焦科技優配息股)",
    topHoldings: [
      { name: "聯發科", weight: 8.2 },
      { name: "台達電", weight: 6.5 },
      { name: "瑞昱", weight: 4.9 },
      { name: "力成", weight: 4.1 }
    ],
    maStrength: 2,
    description: "首檔全電子高股息 ETF。精選財務結構穩健、在 AI 架構大升級中具實質獲利配息之台灣電子股。"
  },
  {
    id: "00878",
    name: "國泰永續高股息",
    symbol: "00878.TW",
    price: 22.40,
    change: 0.15,
    changePercent: 0.67,
    volume: 105000,
    aiPurity: "中高 (約 35% 為 AI 伺服器代工板塊)",
    topHoldings: [
      { name: "廣達", weight: 4.2 },
      { name: "聯發科", weight: 4.1 },
      { name: "緯創", weight: 3.8 },
      { name: "英業達", weight: 3.1 }
    ],
    maStrength: 2,
    description: "高股息人氣王，內嵌多檔 AI 代工與組裝五虎（廣達、緯創等），兼顧抗震性與 AI 機櫃長線紅利。"
  },
  {
    id: "00919",
    name: "群益台灣精選高息",
    symbol: "00919.TW",
    price: 24.15,
    change: 0.18,
    changePercent: 0.75,
    volume: 85000,
    aiPurity: "中高 (約 45% 電子高息與 IC 設計)",
    topHoldings: [
      { name: "聯發科", weight: 9.1 },
      { name: "聯詠", weight: 6.5 },
      { name: "瑞昱", weight: 5.2 },
      { name: "中信金", weight: 4.8 }
    ],
    maStrength: 2,
    description: "篩選高發配率個股。網通晶片與高速傳輸IC設計等高 EPS 受惠股佔比顯著。"
  },
  {
    id: "00927",
    name: "群益半導體收益",
    symbol: "00927.TW",
    price: 18.25,
    change: 0.25,
    changePercent: 1.39,
    volume: 12000,
    aiPurity: "極高 (約 78% 半導體與高息晶片廠)",
    topHoldings: [
      { name: "台積電", weight: 20.8 },
      { name: "聯發科", weight: 18.5 },
      { name: "日月光投控", weight: 9.2 },
      { name: "聯電", weight: 5.1 }
    ],
    maStrength: 3,
    description: "融合半導體成長性與高發配收益，精選台積電、日月光封測與優質 IC 設計，兼備填息實力。"
  },
  {
    id: "00892",
    name: "富邦台灣半導體",
    symbol: "00892.TW",
    price: 15.40,
    change: 0.22,
    changePercent: 1.45,
    volume: 14500,
    aiPurity: "極高 (約 78% 半導體與封測核心)",
    topHoldings: [
      { name: "台積電", weight: 25.0 },
      { name: "聯發科", weight: 15.2 },
      { name: "瑞昱", weight: 6.1 },
      { name: "環球晶", weight: 5.5 }
    ],
    maStrength: 3,
    description: "設有 25% 單一成分股上限，使聯發科、瑞昱等多頭晶片設計股得到更靈活的權重施展空間。"
  },
  {
    id: "00981A",
    name: "主動統一台股增長",
    symbol: "00981A:TPE",
    price: 124.50,
    change: 2.80,
    changePercent: 2.30,
    volume: 18000,
    aiPurity: "極高 (統一主動選股，AI 供應鏈約 78%)",
    topHoldings: [
      { name: "台積電", weight: 35.5 },
      { name: "奇鋐", weight: 10.2 },
      { name: "聯發科", weight: 9.8 },
      { name: "雙鴻", weight: 8.5 }
    ],
    maStrength: 3,
    description: "【特選追蹤主動型基金/ETF】。由統一投信旗艦團隊主動選股操作，重倉佈局散熱雙雄及先進製程，爆發力優於被動指數。"
  },
  {
    id: "00915",
    name: "凱基優選高股息30",
    symbol: "00915.TW",
    price: 26.80,
    change: 0.25,
    changePercent: 0.94,
    volume: 22000,
    aiPurity: "高 (結合多因子篩選之電子高息股)",
    topHoldings: [
      { name: "鴻海", weight: 8.8 },
      { name: "瑞昱", weight: 7.2 },
      { name: "聯詠", weight: 6.8 },
      { name: "新普", weight: 4.5 }
    ],
    maStrength: 3,
    description: "採用獨特多因子動能與低波動篩選。在 AI 伺服器與邊緣升級潮中，獲取極具超額回報的強勢籌碼。"
  },
  // 以下新增 9 檔台股 ETF，補足至 20 檔
  {
    id: "0056",
    name: "元大高股息",
    symbol: "0056.TW",
    price: 41.50,
    change: 0.25,
    changePercent: 0.61,
    volume: 45000,
    aiPurity: "中 (AI 電子代工與散熱廠約 35%)",
    topHoldings: [
      { name: "聯發科", weight: 6.2 },
      { name: "聯詠", weight: 5.5 },
      { name: "廣達", weight: 4.8 },
      { name: "緯創", weight: 4.1 }
    ],
    maStrength: 2,
    description: "歷史最悠久的高股息型。近年納入高股息評等良好的優質 AI 代工與組裝大廠，現金分派穩健。"
  },
  {
    id: "00940",
    name: "元大台灣價值高息",
    symbol: "00940.TW",
    price: 9.85,
    change: 0.05,
    changePercent: 0.51,
    volume: 154000,
    aiPurity: "中 (包含 AI 關鍵代工與週邊零組件廠)",
    topHoldings: [
      { name: "聯電", weight: 7.2 },
      { name: "聯詠", weight: 6.5 },
      { name: "中信金", weight: 5.2 },
      { name: "光寶科", weight: 4.5 }
    ],
    maStrength: 2,
    description: "全台話題性極高的低價、月配型基金。持股注重企業本質現金流，布局多檔高含金量成熟電子大廠。"
  },
  {
    id: "00939",
    name: "統一台灣高息動能",
    symbol: "00939.TW",
    price: 14.50,
    change: -0.05,
    changePercent: -0.34,
    volume: 62000,
    aiPurity: "中高 (聚焦高息電子動能股)",
    topHoldings: [
      { name: "聯發科", weight: 8.5 },
      { name: "大聯大", weight: 6.2 },
      { name: "力成", weight: 5.4 },
      { name: "日月光投控", weight: 4.8 }
    ],
    maStrength: 2,
    description: "專門追蹤具備動能與配息率的優質電子權值，在 AI 與先進封測升級潮中展現較強成長動能。"
  },
  {
    id: "00936",
    name: "台新臺灣IC設計高息",
    symbol: "00936.TW",
    price: 15.20,
    change: 0.18,
    changePercent: 1.20,
    volume: 18500,
    aiPurity: "高 (100% 臺灣中小型 IC 設計龍頭)",
    topHoldings: [
      { name: "聯發科", weight: 9.2 },
      { name: "瑞昱", weight: 8.5 },
      { name: "聯詠", weight: 7.8 },
      { name: "矽創", weight: 4.5 }
    ],
    maStrength: 3,
    description: "全台首檔專為 IC 設計與中長性高股息配發設計。高毛利的晶片設計群在 AI 換機熱中極具優勢。"
  },
  {
    id: "0053",
    name: "元大電子",
    symbol: "0053.TW",
    price: 92.40,
    change: 1.50,
    changePercent: 1.65,
    volume: 3200,
    aiPurity: "極高 (專注臺灣電子與 AI 大廠)",
    topHoldings: [
      { name: "台積電", weight: 48.5 },
      { name: "鴻海", weight: 12.1 },
      { name: "聯發科", weight: 8.5 },
      { name: "廣達", weight: 3.2 }
    ],
    maStrength: 3,
    description: "傳統科技型代表。囊括所有關鍵硬體龍頭，是追隨台積電與 AI 代工全版圖成長的上上之選。"
  },
  {
    id: "00905",
    name: "特選臺灣產業龍頭存股",
    symbol: "00905.TW",
    price: 13.50,
    change: 0.18,
    changePercent: 1.35,
    volume: 11000,
    aiPurity: "高 (各產業龍頭搭配 AI 權值個股)",
    topHoldings: [
      { name: "台積電", weight: 32.5 },
      { name: "鴻海", weight: 8.4 },
      { name: "聯發科", weight: 6.2 },
      { name: "廣達", weight: 2.5 }
    ],
    maStrength: 3,
    description: "重視各產業之王，多重篩選。重金布局具備全球護城河之代工封裝及散熱元件巨擘。"
  },
  {
    id: "00881",
    name: "國泰台灣5G+",
    symbol: "00881.TW",
    price: 24.50,
    change: 0.38,
    changePercent: 1.58,
    volume: 28000,
    aiPurity: "極高 (台灣 5G / AI 通訊半導體精選)",
    topHoldings: [
      { name: "台積電", weight: 30.5 },
      { name: "鴻海", weight: 14.2 },
      { name: "聯發科", weight: 10.5 },
      { name: "台達電", weight: 6.2 }
    ],
    maStrength: 3,
    description: "全台規模最大的通訊科技型。完美對接高速傳輸、5G 基地台、低軌衛星及先進晶片代工。"
  },
  {
    id: "00922",
    name: "國泰台灣領袖50",
    symbol: "00922.TW",
    price: 21.80,
    change: 0.28,
    changePercent: 1.30,
    volume: 14500,
    aiPurity: "高 (結合低碳轉型之 AI 核心企業)",
    topHoldings: [
      { name: "台積電", weight: 32.2 },
      { name: "鴻海", weight: 8.8 },
      { name: "聯發科", weight: 5.5 },
      { name: "廣達", weight: 2.4 }
    ],
    maStrength: 3,
    description: "大型優質市值型變種。在重視低碳轉型的 2026 浪潮中，聚焦最具碳排實力且穩拿 AI 機櫃大單者。"
  },
  {
    id: "00907",
    name: "永豐台灣優選入息",
    symbol: "00907.TW",
    price: 16.50,
    change: 0.12,
    changePercent: 0.73,
    volume: 8500,
    aiPurity: "中 (以大型民生電子與 AI 金融週邊為主)",
    topHoldings: [
      { name: "萬海", weight: 6.5 },
      { name: "統一", weight: 5.8 },
      { name: "聯電", weight: 4.5 },
      { name: "光寶科", weight: 4.2 }
    ],
    maStrength: 2,
    description: "重視現金流入息，波動度小。提供在大環境高度科技震盪時，資產防禦度與配息的雙重緩衝。"
  }
];

export const GLOBAL_TECH_ETFS: Etf[] = [
  {
    id: "00735",
    name: "國泰臺韓科技",
    symbol: "00735.TW",
    price: 36.80,
    change: 0.55,
    changePercent: 1.52,
    volume: 8500,
    aiPurity: "極高 (台積電 + 三星 + Hynix 記憶體)",
    topHoldings: [
      { name: "台積電 (台)", weight: 26.5 },
      { name: "三星電子 (韓)", weight: 22.1 },
      { name: "SK 海力士 (韓)", weight: 14.8 },
      { name: "鴻海 (台)", weight: 8.5 }
    ],
    maStrength: 3,
    description: "【特選追蹤】全台唯一橫跨台韓科技龍頭的 ETF。精準打包台積電與 HBM 記憶體巨頭 SK Hynix，為 AI 算力基礎設施最完整拼圖。"
  },
  {
    id: "00910",
    name: "第一金太空衛星",
    symbol: "00910.TW",
    price: 20.40,
    change: 0.32,
    changePercent: 1.59,
    volume: 6200,
    aiPurity: "高 (AI 網通、低軌道衛星、航太)",
    topHoldings: [
      { name: "波音 (美)", weight: 8.2 },
      { name: "洛克希德馬丁 (美)", weight: 7.8 },
      { name: "台達電 (台)", weight: 4.5 },
      { name: "啟碁 (台)", weight: 4.2 }
    ],
    maStrength: 2,
    description: "【特選追蹤】專注低軌衛星、航太與高速通信。在 AI 邊緣運算及太空互聯網加速建置期，掌握跨國關鍵設備與高階防護系統。"
  },
  {
    id: "00988A",
    name: "主動統一全球創新",
    symbol: "00988A:TPE",
    price: 85.50,
    change: 1.80,
    changePercent: 2.15,
    volume: 15500,
    aiPurity: "極高 (美台日晶片與巨頭主動布局)",
    topHoldings: [
      { name: "NVIDIA (美)", weight: 18.5 },
      { name: "台積電 (台)", weight: 15.2 },
      { name: "Microsoft (美)", weight: 10.5 },
      { name: "東京威力科創 (日)", weight: 6.2 }
    ],
    maStrength: 3,
    description: "【特選追蹤主動型】統一投信主動操盤，打破指数疆界。動態調配美股巨頭（NVDA, MSFT）與台股晶片、散熱巨擘，追求超額阿爾法回報。"
  },
  {
    id: "00830",
    name: "國泰費城半導體",
    symbol: "00830.TW",
    price: 44.20,
    change: 1.15,
    changePercent: 2.67,
    volume: 45000,
    aiPurity: "極高 (美國核心半導體與台積電 ADR)",
    topHoldings: [
      { name: "NVIDIA", weight: 12.5 },
      { name: "Broadcom", weight: 9.8 },
      { name: "AMD", weight: 8.2 },
      { name: "台積電 ADR", weight: 7.5 }
    ],
    maStrength: 3,
    description: "直接追蹤費半指數。囊括美台最頂尖晶片設計、通訊與製造巨星，為全球科技股多頭風向球。"
  },
  {
    id: "00941",
    name: "群益半導體收益",
    symbol: "00941.TW",
    price: 15.80,
    change: 0.22,
    changePercent: 1.41,
    volume: 28000,
    aiPurity: "高 (全球半導體上游設備與材料獨佔廠)",
    topHoldings: [
      { name: "ASML (荷)", weight: 10.2 },
      { name: "信越化學 (日)", weight: 9.5 },
      { name: "應用材料 (美)", weight: 8.8 },
      { name: "東京威力科創 (日)", weight: 7.2 }
    ],
    maStrength: 2,
    description: "主打設備、耗材。AI 擴產必先採購 ASML 光刻機及信越矽晶圓。具高度壟斷和寡占護城河。"
  },
  {
    id: "00757",
    name: "統一FANG+",
    symbol: "00757.TW",
    price: 88.60,
    change: 2.10,
    changePercent: 2.43,
    volume: 12000,
    aiPurity: "極高 (全球 AI 算力與軟體十巨頭)",
    topHoldings: [
      { name: "NVIDIA (美)", weight: 11.5 },
      { name: "Broadcom (美)", weight: 10.8 },
      { name: "Microsoft (美)", weight: 10.2 },
      { name: "Netflix (美)", weight: 9.5 }
    ],
    maStrength: 3,
    description: "精選全球科技極致十巨頭（美股Mag 7 + 台積電/博通）。採等權重再平衡機制，績效彈性極強。"
  },
  {
    id: "00893",
    name: "國泰智能電動車",
    symbol: "00893.TW",
    price: 18.50,
    change: 0.32,
    changePercent: 1.76,
    volume: 18500,
    aiPurity: "高 (AI 晶片與自駕軟硬體)",
    topHoldings: [
      { name: "NVIDIA (美)", weight: 16.5 },
      { name: "AMD (美)", weight: 12.2 },
      { name: "Tesla (美)", weight: 10.5 },
      { name: "台積電 (台)", weight: 5.5 }
    ],
    maStrength: 2,
    description: "專攻電動車、自動駕駛與邊緣運算。納入高比例的 NVIDIA 及 AMD，是藉由車用 AI 布局半導體之首選。"
  },
  {
    id: "00895",
    name: "富邦未來車",
    symbol: "00895.TW",
    price: 24.80,
    change: 0.48,
    changePercent: 1.97,
    volume: 9200,
    aiPurity: "高 (AI 算力、自駕與電動底盤)",
    topHoldings: [
      { name: "NVIDIA (美)", weight: 21.2 },
      { name: "Tesla (美)", weight: 14.5 },
      { name: "台積電 ADR", weight: 9.8 },
      { name: "豐田汽車", weight: 4.5 }
    ],
    maStrength: 3,
    description: "重倉布局 NVIDIA 與台積電 ADR，自駕智能核心佔比高，近期受益於 GPU 及算力需求大漲，走勢極強。"
  },
  {
    id: "00911",
    name: "兆豐洲際半導體",
    symbol: "00911.TW",
    price: 28.20,
    change: 0.65,
    changePercent: 2.36,
    volume: 3100,
    aiPurity: "極高 (美日台歐半導體全明星)",
    topHoldings: [
      { name: "NVIDIA (美)", weight: 10.5 },
      { name: "Broadcom (美)", weight: 9.8 },
      { name: "台積電 ADR", weight: 8.5 },
      { name: "ASML (荷)", weight: 7.8 }
    ],
    maStrength: 3,
    description: "追蹤洲際半導體指數（前身為 SOX）。廣泛持有全球龍頭，對半導體景氣回升及 AI 晶片需求敏感度極高。"
  },
  {
    id: "00762",
    name: "元大全球AI",
    symbol: "00762.TW",
    price: 56.40,
    change: 1.20,
    changePercent: 2.17,
    volume: 5400,
    aiPurity: "極高 (專注全球 AI 軟體、硬體與大模型)",
    topHoldings: [
      { name: "NVIDIA", weight: 15.2 },
      { name: "Microsoft", weight: 12.8 },
      { name: "Alphabet", weight: 10.1 },
      { name: "Meta", weight: 9.2 }
    ],
    maStrength: 3,
    description: "真正專攻「人工智慧」主題的 ETF。除了晶片硬體，更重倉佈局微軟、谷歌等大型語言模型領頭羊。"
  },
  {
    id: "00835",
    name: "富邦NASDAQ",
    symbol: "00835.TW",
    price: 41.50,
    change: 0.68,
    changePercent: 1.67,
    volume: 8800,
    aiPurity: "高 (Nasdaq 100 跨國科技全天候)",
    topHoldings: [
      { name: "Microsoft", weight: 11.5 },
      { name: "Apple", weight: 10.8 },
      { name: "NVIDIA", weight: 9.8 },
      { name: "Amazon", weight: 5.2 }
    ],
    maStrength: 2,
    description: "追蹤那斯達克 100 指數。包含全球各大創新科技、雲端龍頭與 AI 底層基建，為中長期定時定額黃金標的。"
  },
  // 以下新增 9 檔跨國 ETF，補足至 20 檔
  {
    id: "00662",
    name: "富邦NASDAQ-100",
    symbol: "00662.TW",
    price: 85.40,
    change: 1.20,
    changePercent: 1.42,
    volume: 11000,
    aiPurity: "高 (全球科技百強巨頭與 AI 中樞)",
    topHoldings: [
      { name: "Microsoft", weight: 11.2 },
      { name: "Apple", weight: 10.5 },
      { name: "NVIDIA", weight: 9.8 },
      { name: "Amazon", weight: 5.4 }
    ],
    maStrength: 3,
    description: "完整跟隨美國科技百強。自 2026 年生成式 AI 新浪潮以來，直接納入全線 AI 超強軟硬體巨擘。"
  },
  {
    id: "00646",
    name: "元大S&P500",
    symbol: "00646.TW",
    price: 58.30,
    change: 0.65,
    changePercent: 1.13,
    volume: 22000,
    aiPurity: "中高 (美國標普 500 大市值 AI 權值)",
    topHoldings: [
      { name: "Microsoft", weight: 8.5 },
      { name: "NVIDIA", weight: 6.8 },
      { name: "Apple", weight: 6.2 },
      { name: "Amazon", weight: 3.5 }
    ],
    maStrength: 2,
    description: "跟蹤標普 500 指數，最具全球資產定價基礎的大資金首選，納入高純度的美股核心科技股。"
  },
  {
    id: "00861",
    name: "元大全球未來關鍵科技",
    symbol: "00861.TW",
    price: 32.50,
    change: 0.45,
    changePercent: 1.40,
    volume: 4500,
    aiPurity: "極高 (全球半導體、光碟、先進材料上游)",
    topHoldings: [
      { name: "東京威力科創", weight: 8.5 },
      { name: "應用材料", weight: 7.2 },
      { name: "台積電", weight: 6.8 },
      { name: "ASML", weight: 5.5 }
    ],
    maStrength: 3,
    description: "早期半導體上游設備與高值化材料大廠布局。光刻設備廠 (ASML) 與先進晶圓封測比重高。"
  },
  {
    id: "00851",
    name: "台新全球AI",
    symbol: "00851.TW",
    price: 68.45,
    change: 1.15,
    changePercent: 1.71,
    volume: 3200,
    aiPurity: "極高 (專注美日歐大型 AI 頂規龍頭)",
    topHoldings: [
      { name: "NVIDIA", weight: 14.5 },
      { name: "Microsoft", weight: 11.2 },
      { name: "Alphabet", weight: 8.5 },
      { name: "Amazon", weight: 5.2 }
    ],
    maStrength: 3,
    description: "深耕全球 AI 最具霸主地位的領先標的，從主權大模型到關鍵的 GPU 加速網絡通訊無不覆蓋。"
  },
  {
    id: "00926",
    name: "凱基全球行動科技",
    symbol: "00926.TW",
    price: 26.50,
    change: 0.38,
    changePercent: 1.45,
    volume: 5500,
    aiPurity: "高 (全球通訊軟硬體與 AI 移動設備)",
    topHoldings: [
      { name: "Apple", weight: 15.2 },
      { name: "Alphabet", weight: 11.4 },
      { name: "META", weight: 9.5 },
      { name: "NVIDIA", weight: 8.2 }
    ],
    maStrength: 2,
    description: "抓取行動端 AI PC 與智慧型手機的終端換代熱。特別重倉蘋果與谷歌，分享邊緣 AI 收益。"
  },
  {
    id: "00924",
    name: "復華S&P500成長",
    symbol: "00924.TW",
    price: 28.50,
    change: 0.42,
    changePercent: 1.49,
    volume: 12500,
    aiPurity: "高 (聚焦美股標普 500 強勢成長 AI 龍頭)",
    topHoldings: [
      { name: "NVIDIA", weight: 12.8 },
      { name: "Microsoft", weight: 11.5 },
      { name: "Apple", weight: 10.2 },
      { name: "Amazon", weight: 4.8 }
    ],
    maStrength: 3,
    description: "對標標普 500 成長股指數，重組篩選機制，只取高盈餘增長潛力的美股 AI 硬軟十權重。"
  },
  {
    id: "00916",
    name: "國泰全球品牌50",
    symbol: "00916.TW",
    price: 22.40,
    change: 0.28,
    changePercent: 1.27,
    volume: 4100,
    aiPurity: "中 (以高毛利與全球智財品牌為主，包含 AI 巨頭)",
    topHoldings: [
      { name: "Apple", weight: 9.5 },
      { name: "Microsoft", weight: 8.2 },
      { name: "Amazon", weight: 6.5 },
      { name: "NVIDIA", weight: 4.8 }
    ],
    maStrength: 2,
    description: "抓取兼具強勁護城河、定價權和品牌效應的跨國極致龍頭。抗波動性極為優秀。"
  },
  {
    id: "00862",
    name: "富邦全球消費",
    symbol: "00862.TW",
    price: 38.60,
    change: 0.52,
    changePercent: 1.36,
    volume: 1500,
    aiPurity: "中 (全球消費與電商龍頭，AI 用戶聚集地)",
    topHoldings: [
      { name: "Amazon", weight: 14.2 },
      { name: "Tesla", weight: 10.5 },
      { name: "Home Depot", weight: 5.2 },
      { name: "Netflix", weight: 4.8 }
    ],
    maStrength: 2,
    description: "精選優質跨國消費電商、自動駕駛網與流媒體巨頭，受惠於亞馬遜 AWS 與自研晶片大跌起步期。"
  },
  {
    id: "00876",
    name: "元大全球未來通訊",
    symbol: "00876.TW",
    price: 31.80,
    change: 0.45,
    changePercent: 1.43,
    volume: 6200,
    aiPurity: "高 (全球通訊 5G / 6G 網通基礎設施)",
    topHoldings: [
      { name: "台積電", weight: 9.8 },
      { name: "博通", weight: 8.5 },
      { name: "高通", weight: 7.2 },
      { name: "NVIDIA", weight: 5.1 }
    ],
    maStrength: 3,
    description: "高純度打包網通、雷射晶圓製造與特快射頻通道，是長線 AI 多模態交互網路不可或缺的基底資產。"
  }
];

export const NEWS_AND_REPORTS: NewsAndReportsItem[] = [
  {
    id: "news_1",
    type: "news",
    category: "CoWoS & 先進封裝",
    title: "台積電嘉義 CoWoS 廠產能擴充提前：2026 年底單月出貨量將超越 6.5 萬片",
    date: "2026-05-28",
    source: "工商時報",
    impact: "High",
    summary: "台積電因應 NVIDIA Blackwell 及次世代 Rubin 晶片強烈需求，將中科與嘉義先進封裝廠裝機時程提前。供應鏈估算，2026 先進製程與 CoWoS 動能將持續翻倍，相關設備與 ABF 載板出貨熱絡。",
    beneficiaries: ["2330 台積電", "3037 欣興", "TSM"],
    detailText: "根據最新設備供應鏈消息，台積電嘉義廠的整機測試時程因 Blackwell 機櫃拉貨熱潮提早一季啟動。法人預期，此舉將大幅釋放 2026 第三、四季全球高階晶片的供給瓶頸，除代工龍頭直接受益外，長期與先進封裝合作的 ABF 載板龍頭欣興 (3037) 的高多層板需求也將在第三季初顯現爆發性成長。"
  },
  {
    id: "news_2",
    type: "news",
    category: "液冷散熱技術",
    title: "NVIDIA GB300 機櫃規範更新：液冷分流閥與水冷板品質標準拉高，台散熱雙雄獲最大佔比",
    date: "2026-05-27",
    source: "經濟日報",
    impact: "High",
    summary: "由於單櫃功耗在新一代架構中進一步逼近 800kW，散熱系統的精準防漏與冷卻回流規範再度拉高。奇鋐與雙鴻以超過 98% 的出貨良率，成功囊括本波大單，取得產業制高點。",
    beneficiaries: ["3017 奇鋐", "3324 雙鴻", "NVDA"],
    detailText: "隨著 GB300 等超高瓦數 AI 機櫃陸續在各大 Hyperscalers (如微軟、AWS) 數據中心上架，液冷漏水防護被列為一等硬指標。經濟日報指出，奇鋐（3017）與雙鴻（3324）是少數通過 NVIDIA 最新水冷迴路防滲漏二期測試的廠商，將瓜分今年下半年美系雲端巨擘約 80% 的訂單份額，高技術護城河形成高度寡占。"
  },
  {
    id: "news_3",
    type: "news",
    category: "太空通信與網通",
    title: "SpaceX 啟動新一輪「星盾」安全 AI 衛星群發射：台灣網通零組件廠獲包檔急單",
    date: "2026-05-25",
    source: "科技新報",
    impact: "Medium",
    summary: "為提升邊緣端太空運算及低軌道防衛頻寬，太空網通及天線元件需求暴增。第一金太空衛星 (00910) 持股比重高的關鍵台廠已被要求產能預留。",
    beneficiaries: ["00910", "2308 台達電"],
    detailText: "太空運算與低軌道衛星技術日益融合 AI 模型 analysis。SpaceX 的最新「星盾」(Starshield) 安全網路計畫正加大邊緣運算硬體配置，台達電、啟碁等台廠在高壓高頻抗輻射電源與高速接收元件上展現了極佳技術實力，帶動衛星板塊的追捧效應。"
  },
  {
    id: "news_4",
    type: "news",
    category: "晶片與伺服器基盤",
    title: "鴻海取得微軟自研 ASIC 伺服器整機與 B300 晶片基板主力代工合約",
    date: "2026-05-24",
    source: "電子時報",
    impact: "High",
    summary: "微軟為全面擴建亞太與歐美算力中心，新一代自研 Athena 系列晶片基板與伺服器機櫃代工最終敲定。鴻海憑藉大規模 NVLink 架構研發實力奪下本輪大單。",
    beneficiaries: ["2317 鴻海", "MSFT"],
    detailText: "電子時報最新訊息指出，微軟近期對供應鏈下達新指示，下半年將加速鋪設配備自研 ASIC 的Athena伺服器，由台灣鴻海獨家包攬核心基板與整機裝配，出貨能見度直達2027年，預期對鴻海伺服器部門貢獻顯著毛利增長。"
  },
  {
    id: "news_5",
    type: "news",
    category: "TPU與雲端液冷",
    title: "廣達確認與 Google 簽署最新大單：部署次世代 TPU 雲端液冷伺服器機櫃",
    date: "2026-05-23",
    source: "工商時報",
    impact: "High",
    summary: "Google 為因應 Gemini 2.0 大模型推論算力需求，於美、歐多個主要數據園區部署新一代自製 TPU，全面委託廣達進行高瓦數機櫃整機與水冷板系統出貨。",
    beneficiaries: ["2382 廣達", "GOOGL"],
    detailText: "廣達旗下雲達科技（QCT）本次拿下 Google 核心 TPU 訂單，預計將大幅提振公司第三季的高階整機櫃出貨量。由於本次導入最新規格之冷卻迴路與 CDU 系統，每櫃平均售價比前代高出 40% 以上，為近年少見之高毛利大單。"
  },
  {
    id: "news_6",
    type: "news",
    category: "均熱片高階研發",
    title: "健策 ILS 散熱均熱片通過 AMD 新平台驗證，下半年高階出貨單價上調 15%",
    date: "2026-05-22",
    source: "科技新報",
    impact: "Medium",
    summary: "AMD 次世代伺服器處理器專用之高端均熱片，由健策（3653）獨家拿下，良率表現優於原廠預期，為下半年利潤擴張注入強心針。",
    beneficiaries: ["3653 健策", "AMD"],
    detailText: "隨著超微（AMD）AI 生態版圖擴大，旗下核心 CPU/GPU 用之高端超大尺寸均熱片（ILS）需求大幅爆發。健策本週獲原廠官方合格供應商綠燈，順利上調合約單價，進一步防堵其他競爭者切入。"
  },
  {
    id: "news_7",
    type: "news",
    category: "Hyperscale 數據大單",
    title: "緯創旗下緯穎取得 Meta 最新 AI 數據中心合約，全面加速液冷伺服器開發",
    date: "2026-05-20",
    source: "經濟日報",
    impact: "High",
    summary: "Meta 宣佈將大幅增撥资本支出擴建開源 Llama 3 專用集群。緯穎以領先的整機冷卻整合能力奪得其中主力份額，股價與動能續強。",
    beneficiaries: ["6669 緯穎", "3231 緯創", "META"],
    detailText: "Meta 的硬體架構更新計畫向來重視低 PUE 值，緯穎本次以具備超低溫空調與 CDU 整體整合的解決方案獲得青睞。緯創作為大股東也同步享有基板與零組件連鎖拉貨效应，多頭排列格局日益確立。"
  },
  {
    id: "news_8",
    type: "news",
    category: "Blackwell 核心測試",
    title: "京元電子高階 AI 晶片測試產能滿載：NVIDIA Blackwell 測試委託追加急單",
    date: "2026-05-19",
    source: "工商時報",
    impact: "High",
    summary: "最新數據顯示 Blackwell 晶片在封裝後的高階邏輯測試時間比上一代 Hopper 增加近兩倍，京元電（2449）測試產能全面供不應求，法人上調今年盈餘估算。",
    beneficiaries: ["2449 京元電子", "NVDA"],
    detailText: "先進晶片晶圓級測試（CP）與成品測試（FT）時間的暴增，使京元電處於高溢價賣方市場。公司已緊急增購最新高頻測試機台，下半年 Blackwell 測試產能已被美系大廠包檔全包，業績爆發力極強。"
  },
  {
    id: "news_9",
    type: "news",
    category: "高速傳輸介面",
    title: "祥碩高端 PCIe Gen6 重時晶片通過美系主板廠驗證，滲透率將大翻倍",
    date: "2026-05-18",
    source: "電子時報",
    impact: "Medium",
    summary: "AI 伺服器內部多顯示卡高頻寬互聯需求大增，帶動祥碩（5269）高速傳輸重時晶片（Retimer）順利搶進美系一線主機板大廠供應圈。",
    beneficiaries: ["5269 祥碩", "AMZN"],
    detailText: "祥碩在此高端 Retimer 市場正式打破過去由美系大廠獨占的格局，其 PCIe Gen6 方案在功耗與抗電阻干擾上更具性價比。該晶片的批量投片，可望在下半年拉升公司整體毛利率表現。"
  },
  {
    id: "news_10",
    type: "news",
    category: "主權算力佈局",
    title: "英業達攜手美系大廠搶進主權 AI 算力：墨西哥廠新液冷產線全面投產",
    date: "2026-05-15",
    source: "財訊",
    impact: "Medium",
    summary: "為抗衡地緣政治與數據出境限制，各國加緊自建中小型主權 AI 模型。英業達掌握墨西哥與歐洲前哨基地，順利拿下多國算力中心基建外包業務。",
    beneficiaries: ["2356 英業達"],
    detailText: "英業達在美洲擴廠布局近期結出碩果，特別是一體化機櫃測試產線已於墨西哥取得官方環評通過。隨著歐美各政府對資料隱私限制升級，中小型主權算力對英業達這類高度彈性的 OEM/ODM 提供絕佳溢價利潤空間。"
  },
  {
    id: "report_1",
    type: "report",
    category: "大摩研報",
    title: "摩根史坦利 2026 AI 趨勢解密：下一個算力爆發點在「邊緣 AI」與「客製化 ASIC」",
    date: "2026-05-29",
    source: "Morgan Stanley Research",
    impact: "High",
    rating: "Overweight (加碼)",
    targetPrices: [
      { name: "聯發科 (2454)", tp: "1850 元" },
      { name: "Broadcom (AVGO)", tp: "215 美元" }
    ],
    summary: "大摩發布最新科技硬體研究，預警通用 GPU 雖維持高成長，但邊緣運算（如 AI 手機、AI 筆電）及客製化 ASIC 的性價比紅利正在極速爆發，聯發科天璣 9400/9500 平台與 Broadcom 具備高純度投資亮點。",
    beneficiaries: ["2454 聯發科", "AVGO", "QCOM"],
    detailText: "摩根史坦利指出，各大科技巨擘為降低對單一 GPU 的依賴，正加速自研晶片 (ASIC) 的部署。博通 (AVGO) 在以太網路高速交換晶片與 ASIC 設計服務上扮演無可替代的收費站角色；而在邊緣端，聯發科 (2454) 與高通在手持裝置與終端 PC 大模型運算上的突破，將推升 2026 下半年的矽晶圓出貨動能。"
  },
  {
    id: "report_2",
    type: "report",
    category: "元大投顧",
    title: "元大投顧台股 AI 追蹤：看好散熱硬體高單價結構轉型，液冷系統毛利噴發",
    date: "2026-05-26",
    source: "Yuanta Securities Investment",
    impact: "Medium",
    rating: "Buy (買進)",
    targetPrices: [
      { name: "奇鋐 (3017)", tp: "980 元" },
      { name: "雙鴻 (3324)", tp: "1050 元" },
      { name: "主動統一台股增長", tp: "淨值再創新高" }
    ],
    summary: "元大投顧指出，台股散熱零組件受惠於平均單價 (ASP) 翻倍的「液冷系統」(水冷板、分流器、CDU)，毛利率與盈餘預測雙雙調升，主動型基金因持股集中度高，更能攫取此超額獲利。",
    beneficiaries: ["3017 奇鋐", "3324 雙鴻", "00981A"],
    detailText: "元大研究指出，傳統 3D VC 散熱單價約 100-200 美元，但進入全套液冷（CDU、水冷板、分流閥）後，單櫃產值爆增至數萬美元以上。這對奇鋐及雙鴻的財報結構帶來質的飛躍。此類具備超高基本面優勢的個股，最適合主動型經理人靈活、重倉的選股配置策略（如統一台股增長基金、統一全球創新基金）。"
  },
  {
    id: "report_3",
    type: "report",
    category: "麥格理研究",
    title: "麥格理重調美光及台積電投等目標：高頻寬記憶體（HBM3e）缺貨潮蔓延至下半年",
    date: "2026-05-25",
    source: "Macquarie Equities",
    impact: "High",
    rating: "Outperform (優於大盤)",
    targetPrices: [
      { name: "Micron (MU)", tp: "145 美元" },
      { name: "台積電 ADR (TSM)", tp: "230 美元" }
    ],
    summary: "麥格理出具最新記憶體專研，分析當前全系統 GPU 加速均標配超過 192GB 之 HBM3e，各廠封裝端因散熱與層數增加導致良率依舊吃緊，三星、海力士及美光三大巨頭利潤率將攀上歷史高峰。",
    beneficiaries: ["MU", "TSM", "00735"],
    detailText: "研究指出，2026年全球高階 AI 算力配置正經歷強烈的「寬頻記憶體荒」，這使得擁有優質晶圓代工包檔的台積電（2330 / TSM）以及緊密合作的美光（MU）在定價上毫無對手。投資人可透過追蹤高純度臺韓科技（00735）來精準掌握這兩大超強晶片集群的巨額增幅。"
  },
  {
    id: "report_4",
    type: "report",
    category: "高盛評等",
    title: "高盛預期 AI 軟體龍頭 Palantir 商業版圖將呈幾何級爆發，大幅看好長線溢價",
    date: "2026-05-24",
    source: "Goldman Sachs Global",
    impact: "High",
    rating: "Buy (推薦買進)",
    targetPrices: [
      { name: "Palantir (PLTR)", tp: "72 美元" }
    ],
    summary: "高盛最新 analysis 報告強調，Palantir 的企業級 AIP 決策平台在歐美大型製造與金融集團中的滲透速度是前所未見的，其高度安全特性將為公司帶來不可撼動的安全溢價。",
    beneficiaries: ["PLTR", "MSFT"],
    detailText: "高盛分析師在訪談數百家大型 IT 採購負責人後得出結論：算力基建部署完成後，企業的最大支出將急劇轉向高階 AI 決策系統。Palantir（PLTR）透過自研引導式 AI 技術與高彈性 API 系統，具有高黏著度與年費率上調能力，極度看好長線爆發。"
  },
  {
    id: "report_5",
    type: "report",
    category: "花旗研報",
    title: "花旗看好博通 (AVGO) 客製化 ASIC 寡占利潤，重申強力「加碼」並上調晶片目標價",
    date: "2026-05-22",
    source: "Citi Research",
    impact: "High",
    rating: "Buy (強力推薦)",
    targetPrices: [
      { name: "Broadcom (AVGO)", tp: "195 美元" }
    ],
    summary: "花旗研究報告指出，博通在高端 ASIC 市場上幾無對手，除了承接 Google TPU 大單外，美系其他二至三家大型雲端巨擘亦預計在下半年正式投片，推推升博通的設計服務與封裝收入。",
    beneficiaries: ["AVGO", "2454 聯發科", "00988A"],
    detailText: "花旗證券預測，由於以太網 800G 交換機在集群中扮演關鍵加速骨幹角色，博通（AVGO）的網通硬體成長速度甚至一度超越 GPU 通用晶片。與此同時，博通、聯發科聯手的全球主動式創新布局也成為了超額策略（如主動統一全球創新基金）最核心的長跑燃料。"
  },
  {
    id: "report_6",
    type: "report",
    category: "富邦投顧",
    title: "富邦投顧看好聯發科在 Edge AI 頂規晶片的領銜，大幅調高目標價至 NT$ 1950 元",
    date: "2026-05-20",
    source: "Fubon Securities",
    impact: "High",
    rating: "Buy (強力增持)",
    targetPrices: [
      { name: "聯發科 (2454)", tp: "1950 元" }
    ],
    summary: "富邦科技研究主管指出，聯發科天璣系列最新晶片在效能與功耗比上展現了領先同業的優越性，隨著各大品牌主推終端 AI 手機與高端物聯，市佔率將進一步攀至歷史高點。",
    beneficiaries: ["2454 聯發科", "QCOM"],
    detailText: "隨著手機晶片單價的上調，高瓦數處理與散熱功能對周邊 ILS/CDU 要求也跟著激增。聯發科與高階代工封測（京元電、健策）的長期戰略同盟，可望在今年第三季度起為手機與車用平台注入超乎外資預測之盈餘高度。"
  },
  {
    id: "report_7",
    type: "report",
    category: "瑞銀證券",
    title: "瑞銀精細拆解：主動選股型特定基金如何憑借高度持股彈性完勝大盤指數",
    date: "2026-05-18",
    source: "UBS Investment Bank",
    impact: "Medium",
    rating: "Overweight (加碼)",
    targetPrices: [
      { name: "主動統一台股增長", tp: "極高獲利能見度" },
      { name: "主動統一全球創新", tp: "高額收益領跑者" }
    ],
    summary: "瑞銀報告針對台灣上市之主動型與被動型科技 ETFs 進行多因子評比，得出主動型基金在 2026 劇烈分化的 AI 環境下，因為可以重持或避開爭議股，因而創造出近 25% 的超額阿爾法報酬率。",
    beneficiaries: ["00981A", "00988A", "3017 奇鋐"],
    detailText: "瑞銀分析了統一投信的兩檔旗艦主動配置（00981A 與 00988A），認為其重倉水冷散熱模組（奇鋐、雙鴻）與美台核心晶片代工（台積電、輝達）的精準戰術，成功克服了許多被動市值 ETF 必需死守低動能傳產、或爭議個股（如SMCI）的弊病，是現階段台股多頭的首選載體。"
  },
  {
    id: "report_8",
    type: "report",
    category: "美銀證券",
    title: "美銀證券：企業級 AI 模組升級步伐優於預期，Dell Technologies 長線前景穩健",
    date: "2026-05-16",
    source: "Bank of America Research",
    impact: "Medium",
    rating: "Neutral (中性偏多)",
    targetPrices: [
      { name: "Dell (DELL)", tp: "138 美元" }
    ],
    summary: "美銀大科技研報指出，Dell（DELL）在高端液冷伺服器整機裝配與企業混合雲升級中展現了絕佳的工程執行力，在美系中小型硬碟與伺服器組裝中利潤可望逐步回穩。",
    beneficiaries: ["DELL", "NVDA"],
    detailText: "雖然面臨來自代工巨頭（如廣達、鴻海）的市場擠壓，但 Dell 在直接對接傳統非科技五百強企業的伺服器與邊緣儲存櫃安裝上依然擁有無可比擬的全套售後系統，下半年的利潤彈性將隨零組件價格回檔而擴張。"
  },
  {
    id: "report_9",
    type: "report",
    category: "摩根大通",
    title: "小摩分析自研 ASIC 晶片投產爆發：世芯-KY 及創意將共享北美雲端巨擘之巨額溢值",
    date: "2026-05-14",
    source: "J.P. Morgan Advisors",
    impact: "High",
    rating: "Overweight (加碼)",
    targetPrices: [
      { name: "世芯-KY (3661)", tp: "2450 元" },
      { name: "創意 (3443)", tp: "1520 元" }
    ],
    summary: "摩根大通發佈客製化 ASIC (自研特殊功能晶片) 生態白皮書，估計 2026 年自研 ASIC 佔整體 AI 加速器出貨比重將上升至 28%，帶動世芯及創意的高階設計委託（NRE）大單爆滿。",
    beneficiaries: ["3661 世芯-KY", "3443 創意", "2330 台積電"],
    detailText: "小摩報告分析：隨著 Blackwell 與通用 GPU 單片算力昂貴化，亞馬遜、谷歌、Meta與微軟正大力資助世芯-KY與創意進行極具性價比的高階定製項目。台積電先進封裝產能對其 NRE 的無縫支援，也使得世芯在三奈米與五奈米節點上的市佔率高據龍頭地位。"
  },
  {
    id: "report_10",
    type: "report",
    category: "凱基投顧",
    title: "凱基投顧首推國泰臺韓科技 (00735) ETF：兼具台積電代工與三星/海力士 HBM 算力雙翼",
    date: "2026-05-12",
    source: "KGI Securities",
    impact: "High",
    rating: "Outperform (強推買進)",
    targetPrices: [
      { name: "國泰臺韓科技 (00735)", tp: "45 元" }
    ],
    summary: "凱基證券發布重磅大科技主題，分析其為何極力看好 00735 國泰臺韓科技。此 ETF 是國內少數能同時捕獲台積電、三星與海力士三大晶片主宰力量的高流動性產品，堪稱 HBM 投資黃金避風港。",
    beneficiaries: ["00735", "TSM"],
    detailText: "凱基研究員深入分析：未來算力競爭已從單一 GPU 轉向 3D 三維堆疊與超高速記憶體頻寬。00735 一手握著全球晶圓製造制高點（台積電），另一手握著全球 90% 以上 HBM 供貨來源的 SK 海力士與三星，這是在 AI 硬體多頭暴漲階段，最具戰略壟斷地位的 ETF 組態。"
  }
];
